controllers/ProdiLoginController.php
<?php

namespace app\controllers;

use app\models\ProdiLogin;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProdiLoginController implements the CRUD actions for ProdiLogin model.
 */
class ProdiLoginController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all ProdiLogin models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ProdiLogin::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProdiLogin model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProdiLogin model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new ProdiLogin();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['site/login', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ProdiLogin model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ProdiLogin model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProdiLogin model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return ProdiLogin the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProdiLogin::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["site/login"]);
        }
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout = "main-login";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';

?>
<style>
    @import url('https://fonts.googleapis.com/css?family=Patua+One');
    .head {
        color: #3c3c3c;
        background-color: #7f9693;
        height: 50px;
        width: 150px;
        text-align: center;
        border-radius: 20px 20px 20px 20px;
        position: relative;
        top: -10px;
        font-family: "Patua One";
        font-size: 20px;
        margin: 1px;
        padding: 5px 10px 5px 10px;
    }
    .head:hover {
        color: #7f9693;
        background-color: #3c3c3c;
    }
</style>
<div class="site-about">
    <a class="head" href="/basic/web/">About</a>
  
    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
?>

<style>
    @import url('https://fonts.googleapis.com/css?family=Patua+One');
    .head {
        color: #3c3c3c;
        background-color: #7f9693;
        height: 50px;
        width: 150px;
        text-align: center;
        border-radius: 20px 20px 20px 20px;
        position: relative;
        top: -10px;
        font-family: "Patua One";
        font-size: 20px;
        margin: 1px;
        padding: 5px 10px 5px 10px;
    }
    .head:hover {
        color: #7f9693;
        background-color: #3c3c3c;
    }
</style>
<div class="site-contact">
    <a class="head" href="/basic/web/">Contact</a>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<style>
    @import url('https://fonts.googleapis.com/css?family=Abril+Fatface');
    @import url('https://fonts.googleapis.com/css?family=Unlock');
    @import url('https://fonts.googleapis.com/css?family=Stint+Ultra+Expanded');
    @import url('https://fonts.googleapis.com/css?family=Paytone+One');
    .site-index{
        padding: 10px 10px;
        text-align: center;
    }
    .fab.fa-shopify{
        background: #6c7f81; 
        border-radius: 20px 20px 20px 20px; 
        color: #FFFFFF; 
        font-size: 50px;
        padding: 20px 20px;
    }
    .deskripsi{
        font-family: "Abril Fatface";
        text-align: center;
        text-shadow: black 1px 1px 1px;
        font-size: 20px;
        padding-top: 20px;
        padding-bottom: 20px;
    }
    .shop {
        background-color: #aad6d9;
        padding-bottom: 5px;
        padding-top: 20px;
        border-radius: 20px 20px 20px 20px;
    }
    .fas.fa-film{
        background: #aad6d9; 
        border-radius: 20px 20px 20px 20px; 
        color: #FFFFFF; 
        font-size: 50px;
        padding: 20px 20px;
    }
    .movie {
        background-color: #83a0a3;
        padding-bottom: 5px;
        padding-top: 20px;
        border-radius: 20px 20px 20px 20px;
    }
    .fas.fa-cart-plus {
        background: #bec8c8; 
        border-radius: 20px 20px 20px 20px; 
        color: #FFFFFF; 
        font-size: 50px;
        padding: 20px 20px;
    }
    .keranjang {
        background-color: #6c7f81;
        padding-bottom: 5px;
        padding-top: 20px;
        border-radius: 20px 20px 20px 20px;
    }
    .btn.btn-outline-secondary{
        font-family: "Paytone One";
        color: #aad6d9;
        background-color: #83a0a3;
        border-radius: 10px 10px 10px 10px;
    }
    .btn.btn-outline-secondary:hover{
        font-family: "Paytone One";
        color: black;
        background-color: #6c7f81;
        border-radius: 10px 10px 10px 10px;
    }
    .btn.btn-outline-secondary1{
        font-family: "Paytone One";
        color: #aad6d9;
        background-color: #6c7f81;
        border-radius: 10px 10px 10px 10px;
    }
    .btn.btn-outline-secondary1:hover{
        font-family: "Paytone One";
        color: black;
        background-color: #aad6d9;
        border-radius: 10px 10px 10px 10px;
    }
    .btn.btn-outline-secondary2{
        font-family: "Paytone One";
        color: #136161;
        background-color: #aad6d9;
        border-radius: 10px 10px 10px 10px;
    }
    .btn.btn-outline-secondary2:hover{
        font-family: "Paytone One";
        color: black;
        background-color: #bec8c8;
        border-radius: 10px 10px 10px 10px;
    }
    .container1 {
        position: relative;
        width: 100%;
        color: red;
    }
    .judul1{
        position: relative;
        right: -1%;
        top: 5px;
    }
    .judul2{
        position: relative;
        right: -20%;
        top: -51px;
    }
    .judul3{
        position: relative;
        right: -40%;
        top: -107px;
    }
    .menulain{
        position: relative;
        color: black;
        background-color: #aad6d9;
        border: #aad6d9 solid 3px;
        width: 100px;
        left: 20px;
    }
    .menulain:hover{
        color: #6c7f81;
        background-color: #136161;
    }
</style>
<?php

/** @var yii\web\View $this */

$this->title = 'Halaman Utama';
?>
<div class="site-index">
        <div class="row">
            <div class="col-lg-4">
                <div class="shop">
                <i class='fab fa-shopify'></i>
                <h2 class="deskripsi" style="color:#6c7f81">Toko Perlengkapan MHS</h2>
                <p><a class="btn btn-outline-secondary" href="#">TOKO &raquo;</a></p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="movie">
                <i class='fas fa-film'></i>
                <h2 class="deskripsi" style="color:#aad6d9">Movie MHS</h2>
                <p><a class="btn btn-outline-secondary1" href="#">MOVIE &raquo;</a></p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="keranjang">
                <i class='fas fa-cart-plus'></i>
                <h2 class="deskripsi" style="color:#bec8c8">Keranjang MHS</h2>
                <p><a class="btn btn-outline-secondary2" href="#">KERANJANG &raquo;</a></p>
                </div>
            </div>
        </div>

    </div>
</div>
<p class="menulain">Menu Lainnya</p>
<div class="container1">
    <div class="judul1">
        <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" class='btn btn-default' aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Judul1</a>
        <ul aria-labelledby="dropdownSubMenu1" style="background-color: #aad6d9;border-radius:5px 5px 5px 5px;" class="dropdown-menu border-100 shadow">
            <li><a href="#" class="btn btn-default">Some action </a></li>

                <!-- Level two dropdown-->
             
                <!-- End Level two -->
        </ul>
    </div>
    <div class="judul2">
        <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" class='btn btn-default' aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Judul2</a>
        <ul aria-labelledby="dropdownSubMenu1" style="background-color: #aad6d9;border-radius:5px 5px 5px 5px;" class="dropdown-menu border-100 shadow">
            <li><a href="#" class="btn btn-default">Some action </a></li>

                <!-- Level two dropdown-->
             
                <!-- End Level two -->
        </ul>
    </div>
    <div class="judul3">
        <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" class='btn btn-default' aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Judul3</a>
        <ul aria-labelledby="dropdownSubMenu1" style="background-color: #aad6d9;border-radius:5px 5px 5px 5px;" class="dropdown-menu border-100 shadow">
            <li><a href="#" class="btn btn-default">Some action </a></li>

                <!-- Level two dropdown-->
             
                <!-- End Level two -->
        </ul>
    </div>
</div>

views/site/index_old.php
<style>
    @import url('https://fonts.googleapis.com/css?family=Yeseva+One');
 
    .user-reg {
        position: relative;
        right: -6px;
        top: 1px;
        font-family: "Yeseva One";
        font-size: 30px;
        color: #e6e6e6;
        background-color: rgb(84, 84, 84);
        text-shadow: rgb(0, 0, 0) 2px 2px 2px;
    }
    .user-reg:hover{
        color: #bebdbd;
    }
</style>

<?php
use app\models\ProdiLogin;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;


$this->title = 'Starter Page';
?>
<div class="container-fluid">

    <div class="row">
        <div class="col-12 col-sm-6 col-md-3">
            <?= \hail812\adminlte\widgets\InfoBox::widget([
                'text' => 'CPU Traffic',
                'number' => '10 <small>%</small>',
                'icon' => 'fas fa-cog'
            ]
            ) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-6 col-12">
            <?= \hail812\adminlte\widgets\InfoBox::widget([
                'text' => 'Messages',
                'number' => '1,410',
                'icon' => 'far fa-envelope',
            ]) ?>
        </div>
        <div class="col-md-4 col-sm-6 col-12">
            <?= \hail812\adminlte\widgets\InfoBox::widget([
                'text' => 'Events',
                'number' => '41,410',
                'theme' => 'gradient-warning',
                'icon' => 'far fa-calendar-alt',
                'progress' => [
                    'width' => '70%',
                    'description' => '70% Increase in 30 Days'
                ],
            ]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
            <?= \hail812\adminlte\widgets\SmallBox::widget([
                'title' => '150',
                'text' => 'New Orders',
                'icon' => 'fas fa-shopping-cart',
            ]) ?>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
            <?php $smallBox = \hail812\adminlte\widgets\SmallBox::begin([
                'title' => '150',
                'text' => 'New Orders',
                'icon' => 'fas fa-shopping-cart',
                'theme' => 'success'
            ]) ?>
            <?= \hail812\adminlte\widgets\Ribbon::widget([
                'id' => $smallBox->id.'-ribbon',
                'text' => 'Ribbon',
                'theme' => 'warning',
                'size' => 'lg',
                'textSize' => 'lg'
            ]) ?>
            <?php \hail812\adminlte\widgets\SmallBox::end() ?>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 col-12"><a class="user-reg" href="/basic/web/referensi/prodi">
            <?= \hail812\adminlte\widgets\SmallBox::widget([
                'title' => '44',
                'text' => 'User Registrations',
                'icon' => 'fas fa-user-plus',
                'theme' => 'gradient-success',
            ]) ?>
            </a>
        </div>
    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
?>
<div class="card">
    <div class="card-body login-card-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = \yii\bootstrap4\ActiveForm::begin(['id' => 'login-form']) ?>

        <?= $form->field($model,'username', [
            'options' => ['class' => 'form-group has-feedback'],
            'inputTemplate' => '{input}<div class="input-group-append"><div class="input-group-text"><span class="fas fa-envelope"></span></div></div>',
            'template' => '{beginWrapper}{input}{error}{endWrapper}',
            'wrapperOptions' => ['class' => 'input-group mb-3']
        ])
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form->field($model, 'password', [
            'options' => ['class' => 'form-group has-feedback'],
            'inputTemplate' => '{input}<div class="input-group-append"><div class="input-group-text"><span class="fas fa-lock"></span></div></div>',
            'template' => '{beginWrapper}{input}{error}{endWrapper}',
            'wrapperOptions' => ['class' => 'input-group mb-3']
        ])
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-8">
                <?= $form->field($model, 'rememberMe')->checkbox([
                    'template' => '<div class="icheck-primary">{input}{label}</div>',
                    'labelOptions' => [
                        'class' => ''
                    ],
                    'uncheck' => null
                ]) ?>
            </div>
            <div class="col-4">
                <?= Html::submitButton('Sign In', ['class' => 'btn btn-primary btn-block']) ?>
            </div>
        </div>

        <?php \yii\bootstrap4\ActiveForm::end(); ?>

        <div class="social-auth-links text-center mb-3">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-primary">
                <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
            </a>
            <a href="#" class="btn btn-block btn-danger">
                <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
            </a>
        </div>
        <!-- /.social-auth-links -->
        <p class="mb-0">
            <?= Html::a('Register a new membership', ['prodi-login/create'], ['class' => 'text-center']) ?>
        </p>
    </div>
    <!-- /.login-card-body -->
</div>

views/site/login_old.php
<style>
    .container {
        background-color: #b7d1d2;
        padding: 50px;
        border-radius: 20px 20px 20px 20px;
    }
    .btn.btn-primary {
        background-color: #00aebb;
    }
    .btn.btn-primary:hover {
        background-color: #429196;
    }
    .btn.btn-success {
        background-color: #00ff9e;
    }
    .btn.btn-success:hover {
        background-color: #25986c;
    }
    
</style>
<div class="container">
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var app\models\LoginForm $model */

use PhpParser\Node\Stmt\Label;
use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;
use yii\helpers\BaseArrayHelper;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Masukkan Username Dan Password Dengan Benar</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['style' => 'width:100px','class' => ''],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['style'=> 'width:200px','class'=>'text-left','autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput(['style'=> 'width:200px','class'=>'text-left']) ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::a('Create', ['prodi-login/create'], ['class' => 'btn btn-success']) ?>
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <!--<div class="offset-lg-1" style="color:#00008B;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>-->
</div>
</div>